### ISSUE TITLE
Setting up & compiling against non App based

### ISSUE THREAD

**Issue by ceased-ebc** [Visu4link/displee#2]
- Disple mentioned on pastec, no mention on both on how to put together both (note it's for android we will based in the cloud). https://github.com/Visu4link/pastec/

:- How/where data feeds, feed from our DB's (as strings of urls or actual images) into the module and return the data to our DB against the images.

:- Any constraints (i.e we will likely be completing 1-10m images a day)?

Many thanks

**Comment by magwyz** [comment]
Displee is dead project. Its backend was never released in open source.
